version: "3"

services:

  rabbitmq:
    container_name: cn_redis
    build:
      context: ./dockerfile
      dockerfile: Dockerfile
      args:
        - container_name=redis_test
    ports:
      - "5672:5672"
      - "15672:15672"
    expose:
      - "5672"
      - "15672"
